### ISSUE TITLE
 Nothing starts 

### ISSUE THREAD

**Issue by macbentosh** [milesburton/teslacam#4]
I followed the directions and interpreted them how I should to make it work. However when plugged into the car I’m able to activate sentry mode but not access anything on port 3000. Ideas?  Where are the logs. What triggers 3000 to start. I have the power for the pi in constant 5v and the usb into the cars port.

**Comment by milesburton** [comment]
Hi,

There's an issue since one of the recent software updates. It reduces the
current available to the usb, no longer enough to power the pi, you now
need a second power source.

Second issue is the infotainment system expects a partition table which it
didn't have before, I have a fix but haven't had a chance to test it yet.

Finally I've temporary disabled the ui as it draws a lot of power during
start up - I found Dropbox sync was far more useful. I'll restore this one
everything is working again

**Comment by macbentosh** [comment]
I am running double power. Additionally when out of the car nothing is running on :3000. Would love to get this working and test anything you may have.

**Comment by milesburton** [comment]
Sure I'll see what I have when I get home

**Comment by milesburton** [comment]
If you grab the latest code this will now be fixed. There were a number of missing folders that were excluded by mistake

**Comment by th3fallen** [comment]
On this topic when i restart all i get in `ps -ax` is a bunch of defunc methods because `setuidguid` cannot be run by the `pi` user.
